version: 0.2
env:
  variables:
    NODE_ENV: $ENVIRONMENT
phases:
  install:
    commands:
      - ls -lhrt
  pre_build:
    commands:
      - echo $STAGE
      - npm install --force
  build:
    commands:
      - echo $STAGE
      - npm run build
      - ls -la
      - aws s3 rm s3://$SOURCES3BUCKET/ --recursive --exclude "apk-file/*" --exclude "apk-file/*/*"
      - aws s3 sync --delete ./dist/ s3://$SOURCES3BUCKET/ --cache-control "max-age=31536000,public,immutable" --exclude "apk-file/*"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONTDISTRIBUTION --paths "/*"
cache:
  paths:
    - node_modules/**/*
    