const url = 'app/callLogs'

export const callLogsConstants = {
    LOAD_CALLLOGS : `${url}/LOAD_CALLLOGS`,
    LOAD_CALLLOGS_SUCCESS : `${url}/LOAD_CALLLOGS_SUCCESS`,
    LOAD_CALLLOGS_ERROR : `${url}/LOAD_MESSAGES_ERROR`,
    LOAD_CALLLOG_DETAILS : `${url}/LOAD_CALLLOG_DETAILS`,
    LOAD_CALLLOG_DETAILS_SUCCESS : `${url}/LOAD_CALLLOG_DETAILS_SUCCESS`,
    LOAD_CALLLOG_DETAILS_ERROR : `${url}/LOAD_CALLLOG_DETAILS_ERROR`
}