export const chatConstants = {
  // Users
  GET_USERS: 'app/chat/GET_USERS',
  GET_USERS_SUCCESS: 'app/chat/GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'app/chat/GET_USERS_ERROR',

  // Single Conversation
  GET_CONVERSATION: 'app/chat/GET_CONVERSATION',
  GET_CONVERSATION_SUCCESS: 'app/chat/GET_CONVERSATION_SUCCESS',
  GET_CONVERSATION_ERROR: 'app/chat/GET_CONVERSATION_ERROR',

  // Messages
  SEND_MESSAGE: 'app/chat/SEND_MESSAGE',
  SEND_MESSAGE_SUCCESS: 'app/chat/SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_ERROR: 'app/chat/SEND_MESSAGE_ERROR',

  // Real-time message handling
  ADD_MESSAGE: 'app/chat/ADD_MESSAGE',
  RECEIVE_MESSAGE: 'app/chat/RECEIVE_MESSAGE',
  UPDATE_MESSAGE_STATUS: 'app/chat/UPDATE_MESSAGE_STATUS',

  // Select User/Conversation
  SELECT_USER: 'app/chat/SELECT_USER',
  SET_ACTIVE_CONVERSATION: 'app/chat/SET_ACTIVE_CONVERSATION',
  CLEAR_ACTIVE_CONVERSATION: 'app/chat/CLEAR_ACTIVE_CONVERSATION',

  // Create New User/Conversation
  CREATE_USER: 'app/chat/CREATE_USER',
  CREATE_USER_SUCCESS: 'app/chat/CREATE_USER_SUCCESS',
  CREATE_USER_ERROR: 'app/chat/CREATE_USER_ERROR',

  // Clear States
  CLEAR_CHAT_ERROR: 'app/chat/CLEAR_CHAT_ERROR',
  RESET_CHAT_STATE: 'app/chat/RESET_CHAT_STATE',

  // Socket connection
  SOCKET_CONNECTED: 'app/chat/SOCKET_CONNECTED',
  SOCKET_DISCONNECTED: 'app/chat/SOCKET_DISCONNECTED',
};