export const chatConstants = {
  // Stream Chat Token
  GET_STREAM_TOKEN: 'app/chat/GET_STREAM_TOKEN',
  GET_STREAM_TOKEN_SUCCESS: 'app/chat/GET_STREAM_TOKEN_SUCCESS',
  GET_STREAM_TOKEN_ERROR: 'app/chat/GET_STREAM_TOKEN_ERROR',

  // Initialize Chat
  INITIALIZE_CHAT: 'app/chat/INITIALIZE_CHAT',
  INITIALIZE_CHAT_SUCCESS: 'app/chat/INITIALIZE_CHAT_SUCCESS',
  INITIALIZE_CHAT_ERROR: 'app/chat/INITIALIZE_CHAT_ERROR',

  // Users
  GET_USERS: 'app/chat/GET_USERS',
  GET_USERS_SUCCESS: 'app/chat/GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'app/chat/GET_USERS_ERROR',

  // User Channels
  GET_USER_CHANNELS: 'app/chat/GET_USER_CHANNELS',
  GET_USER_CHANNELS_SUCCESS: 'app/chat/GET_USER_CHANNELS_SUCCESS',
  GET_USER_CHANNELS_ERROR: 'app/chat/GET_USER_CHANNELS_ERROR',

  // Select User
  SELECT_USER: 'app/chat/SELECT_USER',
  SET_ACTIVE_CHANNEL: 'app/chat/SET_ACTIVE_CHANNEL',
  
  // Create User
  CREATE_USER: 'app/chat/CREATE_USER',
  CREATE_USER_SUCCESS: 'app/chat/CREATE_USER_SUCCESS',
  CREATE_USER_ERROR: 'app/chat/CREATE_USER_ERROR',

  CREATE_NEW_USER: 'app/chat/CREATE_NEW_USER',
  CREATE_NEW_USER_SUCCESS: 'app/chat/CREATE_NEW_USER_SUCCESS',
  CREATE_NEW_USER_ERROR: 'app/chat/CREATE_NEW_USER_ERROR',

  // Owner Information
  GET_OWNER_INFO: 'app/chat/GET_OWNER_INFO',
  GET_OWNER_INFO_SUCCESS: 'app/chat/GET_OWNER_INFO_SUCCESS',
  GET_OWNER_INFO_ERROR: 'app/chat/GET_OWNER_INFO_ERROR',
};