export const messageConstants = {
  FETCH_MESSAGES: 'app/messages/FETCH_MESSAGES',
  FETCH_MESSAGES_SUCCESS: 'app/messages/FETCH_MESSAGES_SUCCESS',
  FETCH_MESSAGES_ERROR: 'app/messages/FETCH_MESSAGES_ERROR',
  
  SEND_MESSAGE: 'app/messages/SEND_MESSAGE',
  SEND_MESSAGE_SUCCESS: 'app/messages/SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_ERROR: 'app/messages/SEND_MESSAGE_ERROR',
  
  RECEIVE_MESSAGE: 'app/messages/RECEIVE_MESSAGE',
  
  FETCH_CONVERSATIONS: 'app/messages/FETCH_CONVERSATIONS',
  FETCH_CONVERSATIONS_SUCCESS: 'app/messages/FETCH_CONVERSATIONS_SUCCESS',
  FETCH_CONVERSATIONS_ERROR: 'app/messages/FETCH_CONVERSATIONS_ERROR',
  
  FETCH_CASE_DETAILS: 'app/messages/FETCH_CASE_DETAILS',
  FETCH_CASE_DETAILS_SUCCESS: 'app/messages/FETCH_CASE_DETAILS_SUCCESS',
  FETCH_CASE_DETAILS_ERROR: 'app/messages/FETCH_CASE_DETAILS_ERROR',
  
  SET_ACTIVE_CONVERSATION: 'app/messages/SET_ACTIVE_CONVERSATION',
  MARK_AS_READ: 'app/messages/MARK_AS_READ',
};