const url = 'app/postcall'

export const postCallConstants = {
    LOAD_POSTCALL : `${url}/LOAD_POSTCALL`,
    LOAD_POSTCALL_SUCCESS : `${url}/LOAD_POSTCALL_SUCCESS`,
    LOAD_POSTCALL_ERROR : `${url}/LOAD_POSTCALL_ERROR`,
    UPDATE_POSTCALL_FORM : `${url}/UPDATE_POSTCALL_FORM`,
    UPDATE_POSTCALL_FORM_SUCCESS : `${url}/UPDATE_POSTCALL_FORM_SUCCESS`,
    UPDATE_POSTCALL_FORM_ERROR: `${url}/UPDATE_POSTCALL_FORM_ERROR`,
    RESET_SUCCESS : `${url}/RESET_SUCCESS`
}