const url = 'app/user'

export const userConstants = {
    GET_USERS: `${url}/GET_USERS`,
    GET_USERS_SUCCESS: `${url}/GET_USERS_SUCCESS`,
    GET_USERS_ERROR: `${url}/GET_USERS_ERROR`,
    ADD_USER: `${url}/ADD_USER`,
    ADD_USER_SUCCESS: `${url}/ADD_USER_SUCCESS`,
    ADD_USER_ERROR: `${url}/ADD_USER_ERROR`,
    EDIT_USER: `${url}/EDIT_USER`,
    EDIT_USER_SUCCESS: `${url}/EDIT_USER_SUCCESS`,
    EDIT_USER_ERROR: `${url}/EDIT_USER_ERROR`,
    DELETE_USER: `${url}/DELETE_USER`,
    DELETE_USER_SUCCESS: `${url}/DELETE_USER_SUCCESS`,
    DELETE_USER_ERROR: `${url}/DELETE_USER_ERROR`,
    SYNC_TWILIO_NUMBER: `${url}/SYNC_TWILIO_NUMBER`,
    SYNC_TWILIO_NUMBER_SUCCESS: `${url}/SYNC_TWILIO_NUMBER_SUCCESS`,
    SYNC_TWILIO_NUMBER_ERROR: `${url}/SYNC_TWILIO_NUMBER_ERROR`,
    FETCH_TWILIO_NUMBERS: `${url}/FETCH_TWILIO_NUMBERS`,
    FETCH_TWILIO_NUMBERS_SUCCESS: `${url}/FETCH_TWILIO_NUMBERS_SUCCESS`,
    FETCH_TWILIO_NUMBERS_ERROR: `${url}/FETCH_TWILIO_NUMBERS_ERROR`,
    GET_USER_DETAILS: `${url}/GET_USER_DETAILS`,
    GET_USER_DETAILS_SUCCESS: `${url}/GET_USER_DETAILS_SUCCESS`,
    GET_USER_DETAILS_ERROR: `${url}/GET_USER_DETAILS_ERROR`,
    CLEAR:`${url}/CLEAR`
}