const url = 'app/voiceMessage'

export const voiceMailConstants = {
    LOAD_MESSAGES : `${url}/LOAD_MESSAGES`,
    LOAD_MESSAGES_SUCCESS : `${url}/LOAD_MESSAGES_SUCCESS`,
    LOAD_MESSAGES_ERROR : `${url}/LOAD_MESSAGES_ERROR`,
    LOAD_MESSAGE : `${url}/LOAD_MESSAGE`,
    LOAD_MESSAGE_SUCCESS : `${url}/LOAD_MESSAGE_SUCCESS`,
    LOAD_MESSAGE_ERROR : `${url}/LOAD_MESSAGE_ERROR`,
    UPDATE_VOICEMAIL_READ : `${url}/UPDATE_VOICEMAIL_READ`,
    UPDATE_VOICEMAIL_READ_SUCCESS : `${url}/UPDATE_VOICEMAIL_READ_SUCCESS`,
    UPDATE_VOICEMAIL_READ_ERROR : `${url}/UPDATE_VOICEMAIL_READ_ERROR`,
}